<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>test_campaign</name>
  <version>0.0.0</version>
  <description>Test campaign library: orchestrates simulation batches, collects execution traces, stores run records.</description>
  <maintainer email="anonymous@example.com">anonymous</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>psutil</depend>
  <depend>rclpy</depend>
  <depend>test_campaign_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <exec_depend>quadruped_example_skillset_client</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
